### ISSUE TITLE
make data exception error

### ISSUE THREAD

**Issue by estatistics** [arielf/speedtests#1]
following your instructions....
terminal output this....

elias@eliasc:~/speedtests$ make data
logname: no login name
logname: no login name
logname: no login name
logname: no login name
logname: no login name
logname: no login name
logname: no login name
logname: no login name
#
logname: no login name
# Collect internet speed data into Data/.2021-11-08.tsv
#
mkdir -p Data
./my-speedtest.many > Data/.2021-11-08.tsv.tmp && \
	mv Data/.2021-11-08.tsv.tmp Data/.2021-11-08.tsv
Collecting speed data on 20 data-centers...
YYYY-MM-DD-HH:MM     Ping(ms) Upload  Download  Provider (Distance)
Traceback (most recent call last):
  File "/usr/bin/speedtest", line 11, in <module>
    load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest')()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1986, in main
    shell()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1872, in shell
    speedtest = Speedtest(
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1091, in __init__
    self.get_config()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1173, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''
Illegal division by zero at ./my-speedtest.many line 138.
make: *** [Makefile:28: Data/.2021-11-08.tsv] Error 1

**Comment by arielf** [comment]
Hi There
Thanks for the report.

`logname` is a standard Linux utility, part of `coreutils`.

What env/OS is this running in?

Can you try and install coreutils and see if this solved the issue?
Please make sure `logname` exists and returns your username when called from your shell.
Also note that the Makefile is a GNU Make Makefile.

Thanks again for reporting!

**Comment by TilKenneth** [comment]
I did not have LOGNAME defined. Ubuntu/WSL2 with all reqs.

`echo $LOGNAME` works, but only capitalized.

**Comment by arielf** [comment]
Added two possible fallbacks to caling the logname utility.

But I don't have WSL so can't be sure if my attempt at fixing this works in your env :-)

Anyway, would be cool if you could test/verify.  Thanks.

**Comment by TilKenneth** [comment]
Hey, sure. Here are some comments.

It is an OR so it will get "ran", but the changes meet expected outcome.

```
kenneth@arielf:~/speedtests$ make
logname: no login name
logname: no login name
logname: no login name
logname: no login name
./check-prereqs
logname: no login name
Cool: base program make is installed
Cool: base program perl is installed
Cool: base program speedtest-cli is installed
Cool: base program Rscript is installed
Cool: R package ggplot2 is installed
Cool: R package data.table is installed
Cool: R package scales is installed
logname: no login name
logname: no login name
logname: no login name
logname: no login name
#
logname: no login name
# Collect internet speed data into Data/kenneth.2023-01-03.tsv
#
mkdir -p Data
./my-speedtest.many > Data/kenneth.2023-01-03.tsv.tmp && \
        mv Data/kenneth.2023-01-03.tsv.tmp Data/kenneth.2023-01-03.tsv
Collecting speed data on 20 data-centers...
YYYY-MM-DD-HH:MM     Ping(ms) Upload  Download  Provider (Distance)
....
speed-test by server success rate: 10/10 = 100.00%
logname: no login name
logname: no login name
#
logname: no login name
# Generate upload+download speed scatter-plot from Data/kenneth.2023-01-03.tsv
#
./speedtests.R Data/kenneth.2023-01-03.tsv
argvN=Data/kenneth.2023-01-03.tsv
Saved chart in Data/kenneth.2023-01-03.tsv.png
kenneth@arielf:~/speedtests$
```

I suggest a change in https://github.com/arielf/speedtests/blob/d969428f80b4d6618c65bf136e34fb915edb855f/check-prereqs#L50

https://github.com/arielf/speedtests/blob/d969428f80b4d6618c65bf136e34fb915edb855f/check-prereqs#L60

Instead of 'Cool', (international) users might expect OK / FAIL for this output. I was unexpected for me at least.



Another nitpick is add `-v` to `mkdir/mv/cp`.

```
kenneth@arielf:~/speedtests$ mkdir -vp Data2
mkdir: created directory 'Data2'
```

And add test to check if $(DATA_FILE) exists (or failed to mkdir), if not, fail/stop?

The mv of `.tsv.tmp -> .tsv` does not occur, even if it exists (I just added --secure to test this):
```
speed-test by server success rate: 1/10 = 10.00%
make: *** [Makefile:28: Data/files/kenneth.2023-01-03.tsv] Error 1
```

https://github.com/arielf/speedtests/blob/d969428f80b4d6618c65bf136e34fb915edb855f/Makefile#L27-L29


There is still valid data in .tsv even if `my-speedtest.many` exit code is non-success. Personally if there are more than 1 data points, the graph should be generated, because that is the purpose of this tool.

https://github.com/arielf/speedtests/blob/d969428f80b4d6618c65bf136e34fb915edb855f/my-speedtest.many#L156-L163




I add these comments because this issue is about error/wrong/unexpected output.
